- user:
    name: emilien
    shell: /bin/zsh
  become: true

- name: Install the rpmfusion repo packages
  dnf:
    name={{ item }}
    state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
  become: true

- name: Install packages
  dnf: name={{ item }}
  with_items: "{{ package_list }}"
  become: true

- name: Deploy directories
  file:
    path: /home/{{ home_user }}/{{ item }}
    state: directory
  with_items: "{{ directory_list }}"

- name: Cleanup directories
  file:
    path: /home/{{ home_user }}/{{ item }}
    state: absent
  with_items: "{{ absent_directory_list }}"

- name: Deploy oh-my-zsh git fork
  git:
    repo: 'https://github.com/EmilienM/oh-my-zsh.git'
    dest: /home/{{ home_user }}/git/EmilienM/oh-my-zsh
    version: emilien

- stat:
    path: /home/{{ home_user }}/.zshrc
  register: zshrc

- name: Install oh-my-zsh
  shell: /home/{{ home_user }}/git/EmilienM/oh-my-zsh/tools/install.sh
  when: zshrc.stat.islnk is not defined

- name: Update oh-my-zsh git fork
  git:
    repo: 'https://github.com/EmilienM/oh-my-zsh.git'
    dest: /home/{{ home_user }}/.oh-my-zsh
    version: emilien

- name: Deploy .gitconfig
  template:
    src: gitconfig
    dest: /home/{{ home_user }}/.gitconfig

- name: Install Gertty from source
  pip:
    name: git+https://github.com/openstack/gertty
  become: true

- name: Deploy .gertty.yaml
  template:
    src: gertty.yaml
    dest: /home/{{ home_user }}/.gertty.yaml
    mode: '0600'

- name: Configure Terminator
  template:
    src: terminator
    dest: /home/{{ home_user }}/.config/terminator/config

- name: Deploy awesome-copycats fork
  git:
    repo: 'https://github.com/EmilienM/awesome-copycats.git'
    dest: /home/{{ home_user }}/.config/awesome
    version: emilien

- name: Deploy awesome configuration
  copy:
    src: /home/{{ home_user }}/.config/awesome/rc.lua.template
    dest: /home/{{ home_user }}/.config/awesome/rc.lua

- name: Deploy vim configuration
  git:
    repo: 'https://github.com/EmilienM/grimvim.git'
    dest: /home/{{ home_user }}/.vim
    version: emilien

- stat:
    path: /home/{{ home_user }}/.vim/autoload/plug.vim
  register: plugvim

- name: Deploy vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ home_user }}/.vim/autoload/plug.vim
  when: plugvim.stat.islnk is not defined

- name: Manage .vimrc
  file:
    src: /home/{{ home_user }}/.vim/vimrc
    dest: /home/{{ home_user }}/.vimrc
    state: link

- stat:
    path: /home/{{ home_user }}/.vimrc
  register: vimrc

- name: Notify that vi needs manual command to deploy plugins
  debug:
    msg: "Run vi and :PlugInstall to deploy plugins."
  when: vimrc.stat.islnk is not defined

- name: Deploy secret files
  git:
    repo: 'git.macchi.pro:/srv/git/backup.git'
    dest: /home/{{ home_user }}/git/EmilienM/backup


# TODO:
# - zshrc_extra
# - weechat
# - vim
# - packages
