- name: Install the rpmfusion repo packages
  dnf:
    name={{ item }}
    state=present
  with_items:
    - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm
    - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm
  become: true

- name: Install packages
  dnf: name={{ item }}
  with_items: "{{ package_list }}"
  become: true

- name: Install git directory
  file:
    path: /home/{{ home_user }}/{{ item }}
    state: directory
  with_items: "{{ directory_list }}"

- name: Deploy oh-my-zsh git fork
  git:
    repo: 'https://github.com/EmilienM/oh-my-zsh.git'
    dest: /home/{{ home_user }}/git/EmilienM/oh-my-zsh
    version: emilien

- name: Install oh-my-zsh
  shell: /home/{{ home_user }}/git/EmilienM/oh-my-zsh/tools/install.sh

- name: Update oh-my-zsh git fork
  git:
    repo: 'https://github.com/EmilienM/oh-my-zsh.git'
    dest: /home/{{ home_user }}/.oh-my-zsh
    version: emilien


- name: Deploy .gitconfig
  template:
    src: gitconfig
    dest: /home/{{ home_user }}/.gitconfig

- name: Deploy .gertty.yaml
  template:
    src: gertty.yaml
    dest: /home/{{ home_user }}/.gertty.yaml

# TODO:
# - gertty
# - zshrc_extra
# - awesome
# - weechat
# - vim
# - packages
# - terminator
