---

- name: Include server variables
  include_vars: server.yml

# EPEL tasks stolen from:
# http://yallalabs.com/linux/how-to-install-epel-repository-with-ansible-on-centos-7-rhel-7/
- name: Check if EPEL repo is already configured
  stat: path={{ epel_repofile_path }}
  register: epel_repofile_result

- name: Install EPEL repo
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  register: result
  when: not epel_repofile_result.stat.exists
  become: true

- name: Import EPEL GPG key
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: not epel_repofile_result.stat.exists
  become: true

- name: Install packages
  yum: name={{ item }}
  with_items: "{{ package_list }}"
  become: true

- name: Deploy directories
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ directory_list }}"
  become: true

- name: Cleanup directories
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ absent_directory_list }}"
  become: true

- name: Deploy secret files
  git:
    repo: 'git.macchi.pro:/srv/git/backup.git'
    dest: /home/{{ home_user }}/git/EmilienM/backup

- name: Deploy oh-my-zsh git fork
  git:
    repo: 'https://github.com/EmilienM/oh-my-zsh.git'
    dest: /home/{{ home_user }}/git/EmilienM/oh-my-zsh
    version: emilien

- name: Check if zshrc is configured
  stat:
    path: /home/{{ home_user }}/.zshrc
  register: zshrc

- name: Install oh-my-zsh
  shell: /home/{{ home_user }}/git/EmilienM/oh-my-zsh/tools/install.sh
  when: zshrc.stat.islnk is not defined

- name: Update oh-my-zsh git fork
  git:
    repo: 'https://github.com/EmilienM/oh-my-zsh.git'
    dest: /home/{{ home_user }}/.oh-my-zsh
    version: emilien

- user:
    name: emilien
    shell: /bin/zsh
  become: true

- name: Deploy .gitconfig
  template:
    src: gitconfig
    dest: /home/{{ home_user }}/.gitconfig

- name: Deploy vim configuration
  git:
    repo: 'https://github.com/EmilienM/grimvim.git'
    dest: /home/{{ home_user }}/.vim
    version: emilien

- name: Ensure .vim/autoload exists
  file:
    path: /home/{{ home_user }}/.vim/autoload
    state: directory

- name: Check if vim-plug is deployed
  stat:
    path: /home/{{ home_user }}/.vim/autoload/plug.vim
  register: plugvim

- name: Deploy vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: /home/{{ home_user }}/.vim/autoload/plug.vim
  when: plugvim.stat.islnk is not defined

- name: Manage .vimrc
  file:
    src: /home/{{ home_user }}/.vim/vimrc
    dest: /home/{{ home_user }}/.vimrc
    state: link

- name: Check if vimrc is configured
  stat:
    path: /home/{{ home_user }}/.vimrc
  register: vimrc

- name: Notify that vi needs manual command to deploy plugins
  debug:
    msg: "Run vi and :PlugInstall to deploy plugins."
  when: vimrc.stat.islnk is not defined

- name: Check if weechat is configured
  stat:
    path: /home/{{ home_user }}/.weechat/weechat.conf
  register: weechat

- name: Manage weechat configuration
  shell: cp -r /home/{{ home_user }}/git/EmilienM/backup/weechat/* /home/{{ home_user }}/.weechat/
  when: weechat.stat.islnk is not defined

- name: Configure OpenVPN
  copy:
    src: "{{ item }}"
    dest: /etc/openvpn
    owner: root
    mode: 0700
  with_fileglob:
    - '/home/{{ home_user }}/git/EmilienM/backup/openvpn/server/*'
  become: true

- name: Make sure openvpn is running
  systemd:
    enabled: true
    state: started
    name: openvpn@server.service
  become: true

- name: Make sure ufw is running
  systemd:
    enabled: true
    state: started
    name: ufw
  become: true

- name: Allow everything and enable UFW
  ufw:
    state: enabled
    policy: allow
  become: true

- name:  Set ufw logging
  ufw:
    logging: medium
  become: true

- name: Open SSH in firewall
  ufw:
    rule: limit
    port: 22
    proto: tcp
  become: true

- name: Open Nginx in firewall
  ufw:
    rule: allow
    port: 8443
    proto: tcp
  become: true

- name: Open OpenVPN in firewall
  ufw:
    rule: allow
    port: 443
    proto: tcp
  become: true

- name: Open GlowingBear in firewall
  ufw:
    rule: allow
    port: 8773
    proto: tcp
  become: true

- name: Open ZNC in firewall
  ufw:
    rule: allow
    port: 6665
    proto: tcp
  become: true

- name: Check if letsencrypt is configured
  stat:
    path: /etc/letsencrypt/accounts
  register: letsencrypt
  become: true

- name: Manage letsencrypt configuration
  shell: cp -r /home/{{ home_user }}/git/EmilienM/backup/letsencrypt/* /etc/letsencrypt/
  when: letsencrypt.stat.islnk is not defined
  become: true

- name: Secure letsencrypt configuration
  file:
    path: /etc/letsencrypt
    mode: 0400
    owner: root
    state: directory
  when: letsencrypt.stat.islnk is not defined
  become: true

- name: Make sure fail2ban is running
  systemd:
    enabled: true
    state: started
    name: fail2ban
  become: true

- name: Install transmission
  yum:
    name: transmission
    exclude: transmission-gtk
  become: true


# TODO:
# - nginx
# - owncloud server
# - znc
# - glowingbear
# - transmission
# - emby
